### ISSUE TITLE
Probabilities returned when 'impute.missing=FALSE'

### ISSUE THREAD

**Issue by mrhumanzee** [kosukeimai/wru#82] opened 2022-10-05 17:07 UTC
Running the command below gives a warning that the last name of one individual cannot be matched to to the Census list.
`df_omitt_missing = predict_race(voter.file = voters, 
                                  surname.only = T,
                                  impute.missing = FALSE)`
Looking at the data frame _df_omitt_missing_ reveals that the individual with the surname "Wantcheckon" is assigned a probability of 0.2 for each of the 5 racial categories.  Does the function _predict_race()_ assign this set of probabilities to surnames it cannot find in the Census list?

I also have a slightly unrelated question. How does _predict_race()_ even calculate probabilities when _surname.only = T_ and a surname cannot be found in the Census?

**Comment by 1beb** [comment] 2022-10-05 17:19
When `surname.only = TRUE`, we use a default race.marginal that ought to be the national race margin. You can adjust this in the arguments. if you're interested in where this happens in the code:

https://github.com/kosukeimai/wru/blob/main/R/race_prediction_funs.R#L274

**Comment by mrhumanzee** [comment] 2022-10-05 17:44
> When `surname.only = TRUE`, we use a default race.marginal that ought to be the national race margin. You can adjust this in the arguments. if you're interested in where this happens in the code:
> 
> https://github.com/kosukeimai/wru/blob/main/R/race_prediction_funs.R#L274

Hello 1beb, the code that you linked to suggests  (although please correct me if I am wrong) that I should have obtained the following probabilities for the surname "Wantcheckon".
```
 race.margin <- c(r_whi=0.5783619, r_bla=0.1205021, r_his=0.1872988,
                   r_asi=0.06106737, r_oth=0.05276981)
```
I did not obtain these probabilities. Instead, I obtained the probabilities pr(white) = 0.1016771922, pr(black) = 0.2873197891, pr(Hispanic) = 0.3838356390, pr(Asian) =0.06225610, and pr(other) = 0.16491128. Furthermore, these racial probabilities for "Wantcheckon" varied based on the other surnames in the data frame _voters_. E.g., I added the surname "xyqyxxxzx" which I knew would not be in the Census list. After I did this, I got a new set of probabilities for "Wantcheckon": pr(white) = 0.0992409984, pr(black) = 0.2884606925, pr(Hispanic) = 0.3861093343, pr(Asian) = 0.06232167, pr(other) = 0.16386730. Is there a reason for this?

**Comment by robincrlee** [comment] 2022-10-11 18:58
@mrhumanzee I wasn't able to reproduce your result. 

When I ran `df_omitt_missing = predict_race(voter.file = voters, surname.only = T, impute.missing = FALSE)`, I did get the same probabilities as the race.margin probabilities for the surname Wantchekon`(r_whi=0.5783619, r_bla=0.1205021, r_his=0.1872988, r_asi=0.06106737, r_oth=0.05276981)`. 

My wru version is 
> packageVersion("wru")
[1] ‘1.0.1’

**Comment by 1beb** [comment] 2022-10-11 19:01
@mrhumanzee can you post `sessionInfo()`?

**Comment by mrhumanzee** [comment] 2022-10-11 19:48
> @mrhumanzee can you post `sessionInfo()`?

Here you go:

```
R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8    LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                           LC_TIME=English_United States.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] wru_1.0.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.9        PL94171_1.1.2     pillar_1.8.1      compiler_4.2.1    tools_4.2.1       digest_0.6.29    
 [7] lubridate_1.8.0   jsonlite_1.8.2    memoise_2.0.1     lifecycle_1.0.3   tibble_3.1.8      pkgconfig_2.0.3  
[13] rlang_1.0.6       cli_3.4.1         curl_4.3.3        parallel_4.2.1    fastmap_1.1.0     furrr_0.3.1      
[19] dplyr_1.0.10      stringr_1.4.1     httr_1.4.4        fs_1.5.2          generics_0.1.3    vctrs_0.4.2      
[25] gitcreds_0.1.2    globals_0.16.1    tidyselect_1.2.0  glue_1.6.2        listenv_0.8.0     R6_2.5.1         
[31] gh_1.3.1          fansi_1.0.3       parallelly_1.32.1 piggyback_0.1.4   purrr_0.3.5       magrittr_2.0.3   
[37] codetools_0.2-18  future_1.28.0     utf8_1.2.2        stringi_1.7.8     cachem_1.0.6 
```
I am not able to update my version of wru to 1.0.1 via the command update.packages("wru"). Is this something I have to do manually?

**Comment by 1beb** [comment] 2022-10-11 19:50
Yes, we have not yet pushed the fix for this bug to CRAN because we discovered it shortly after we had already successfully submitted. For now, you can install using remotes: 

```
remotes::install_github('kosukeimai/wru')
```

**Closed by 1beb** 2022-10-11 19:50 UTC

**Comment by mrhumanzee** [comment] 2022-10-11 20:07
1beb, installing the most recent version of wru fixed the problem. I was able to obtain the correct probabilities running the command `df_omitt_missing = predict_race(voter.file = voters, surname.only = T, impute.missing = FALSE)`,
