### ISSUE TITLE
Errors given block and Surname 

### ISSUE THREAD

**Issue by robincrlee** [kosukeimai/wru#80] opened 2022-10-05 01:20 UTC
I am using the voters sample file. 
When trying to make imputation using block level demographics, I ran into some errors. 

1. A block was not found using 2010 census

`predict_race(voter.file = voters, surname.only = F, census.geo = "block", census.key = key)`

```Error in census_helper_new(key = census.key, voter.file = voter.file,  : 
  The following locations in the voter.file are not available in the census data (listed as state-county-tract-block):
NJ-021-004000-1025
```

2. Bad API format when requesting census data at block level at 2020 census 
`predict_race(voter.file = voters, surname.only = F, census.geo = "block", census.key = key, year = "2020")`

Even thought after specifying year as 2020, the URL at block level shown up in the error message points to 2010.

```
Running block by county...
County 1 of 1: 021
Error in file(con, "r") : 
  cannot open the connection to 'https://api.census.gov/data/2010/dec/sf1?key=..&get=P2_005N,P2_006N,P2_007N,P2_008N,P2_009N,P2_010N,P2_011N,P2_002N&for=tract:*&in=state:34+county:021'
In addition: Warning message:
In file(con, "r") :
  cannot open URL 'https://api.census.gov/data/2010/dec/sf1?key=..&get=P2_005N,P2_006N,P2_007N,P2_008N,P2_009N,P2_010N,P2_011N,P2_002N&for=tract:*&in=state:34+county:021': HTTP status was '400 Bad Request'
Try census server again: https://api.census.gov/data/2010/dec/sf1?
Error in file(con, "r") : 
  cannot open the connection to 'https://api.census.gov/data/2010/dec/sf1?key=..&get=P2_005N,P2_006N,P2_007N,P2_008N,P2_009N,P2_010N,P2_011N,P2_002N&for=tract:*&in=state:34+county:021'
In addition: Warning message:
In file(con, "r") :
  cannot open URL 'https://api.census.gov/data/2010/dec/sf1?key=..&get=P2_005N,P2_006N,P2_007N,P2_008N,P2_009N,P2_010N,P2_011N,P2_002N&for=tract:*&in=state:34+county:021': HTTP status was '400 Bad Request'
```

**Comment by 1beb** [comment] 2022-10-05 01:41
Please note you are sharing your API key. Recommend snipping from the links.

**Comment by 1beb** [comment] 2022-10-05 01:43
I will investigate this. It looks like when asked to use 2010, it uses the census variable names for 2020. I think the problem is somewhere around here: 

https://github.com/kosukeimai/wru/blob/main/R/census_geo_api.R#L72

**Comment by 1beb** [comment] 2022-10-05 02:28
Ok, quick review here: 

1. This is a bug, technically, it was 2010 not found in 2020 tract/block.
2. Same bug, pointed to the wrong decennial API link. 

I'm going to post a PR that will fix the issue, but it will still fail because the census tract in NJ doesn't exist in 2020 in the voters data. 

```
library(wru)
library(future)
data(voters)
plan(multisession)
voters <- dplyr::filter(voters, surname != "Ratkovic")
predict_race(voter.file = voters, surname.only = F, census.geo = "block", year = 2010)
  VoterID    surname state CD county  tract block precinct age sex party PID
1       1     Khanna    NJ 12    021 004000  3001        6  29   0   Ind   0
2       2       Imai    NJ 12    021 004501  1025           40   0   Dem   1
6       3     Rivera    NY 12    061 004800  6001           33   0   Rep   2
3       4    Fifield    NJ 12    021 004501  1025           27   0   Dem   1
4       5       Zhou    NJ 12    021 004501  1025           28   1   Dem   1
7       7    Johnson    NY  9    061 015100  4000           25   0   Dem   1
5       8      Lopez    NJ 12    021 004501  1025           33   0   Rep   2
9       9 Wantchekon    NJ 12    021 004501  1025           50   0   Rep   2
8      10      Morse    DC  0    001 001301  3005           29   1   Rep   2
  place       last     first    pred.whi     pred.bla     pred.his   pred.asi
1 74000     Khanna     Kabir 0.132181564 1.277004e-02 2.579207e-02 0.76408266
2 60900       Imai    Kosuke 0.013796609 9.157890e-05 3.284977e-03 0.97390570
6 51000     Rivera    Carlos 0.063648606 8.393921e-03 8.052065e-01 0.11898290
3 60900    Fifield       Ben 0.920963133 5.146772e-04 7.794942e-03 0.05886873
4 60900       Zhou Yang-Yang 0.001292866 6.689279e-05 2.380431e-05 0.99825487
7 51000    Johnson     Frank 0.763145285 1.279784e-01 1.274556e-02 0.05084411
5 60900      Lopez   Gabriel 0.123734525 4.093378e-03 6.649947e-01 0.19951201
9 60900 Wantchekon   Leonard 0.557969459 8.601017e-02 1.532035e-01 0.18636259
8 50000      Morse     Julia 0.964285652 4.092222e-03 8.766617e-03 0.00000000
      pred.oth
1 0.0651736697
2 0.0089211320
6 0.0037680347
3 0.0118585205
4 0.0003615693
7 0.0452866914
5 0.0076653717
9 0.0164543248
8 0.0228555092

```

**Comment by 1beb** [comment] 2022-10-05 03:07
@robincrlee Can you try running your code with: 

```
remotes::install_github("kosukeimai/wru", ref = "issue_80") 
```

**Comment by robincrlee** [comment] 2022-10-05 18:05
Since the NJ-021-004501 -1025 is not a valid 2010 state-county-tract-block identifier, would it make sense to modify the fake data `voters`?

**Comment by robincrlee** [comment] 2022-10-05 18:13
Thanks for the quick fixes, @1beb !

I was able to install using the issue_80 branch. 

`predict_race(voter.file = voters, surname.only = F, census.geo = "block", census.key = key, year = "2020")`

When running this function, I was able to download the tract level data without url pointing to 2010. 

As far as using 2020 at block/block-group level goes, this fix seems to work. I also like how you allow for both "2020" and 2020 accepted as valid argument in this fix :)

**Comment by robincrlee** [comment] 2022-10-05 18:16
A related comment. But definitely should be a feature request as a separate issue. 

I wonder if it would be desirable to have a function to check if input (voter files/address data) data contains valid tract/block identifier for the given census year. Right now, get_census_data would acquire data first, and then try to look up the input data geographic identifier.

**Comment by 1beb** [comment] 2022-10-05 18:33
Thanks @robincrlee I'll note these other adjustments in separate issues, and close this one.

**Closed by 1beb** 2022-10-05 18:33 UTC
